# Generated by Django 4.2.3 on 2023-09-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='likedPosts',
        ),
    ]
