# Generated by Django 4.2.3 on 2023-09-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_remove_user_likedposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='isLiked',
            field=models.BooleanField(default=False),
        ),
    ]
