# Generated by Django 4.2.3 on 2023-08-23 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_tweets_profiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='tweetText',
            new_name='post',
        ),
    ]
